# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-25 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id_user', models.IntegerField(verbose_name='ID клиента')),
                ('promocode', models.CharField(default='', max_length=10, verbose_name='Промокод')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='Название товара')),
                ('count', models.IntegerField(default=0, verbose_name='Количество товара')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость товара')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tobacco',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='Название табака')),
                ('weight', models.IntegerField(default=0, verbose_name='Количество табака')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость табака')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='food',
            field=models.ManyToManyField(blank=True, to='stock.Food'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tobaccos',
            field=models.ManyToManyField(blank=True, to='stock.Tobacco'),
        ),
    ]
