# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-26 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='food',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='tobaccos',
        ),
        migrations.AddField(
            model_name='bill',
            name='sum',
            field=models.IntegerField(default=0, verbose_name='Итоговая сумма'),
        ),
    ]
