# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tobacco',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость табака'),
        ),
        migrations.AlterField(
            model_name='tobacco',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Количество табака'),
        ),
    ]
