# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20170827_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='Название товара')),
                ('count', models.IntegerField(default=0, verbose_name='Количество товара')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
