# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id_user', models.IntegerField(verbose_name='ID клиента')),
                ('promocode', models.CharField(default='', max_length=10, verbose_name='Промокод')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
