# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_historicalbill_historicalfood_historicaltobacco'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость товара'),
        ),
        migrations.AddField(
            model_name='historicalfood',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость товара'),
        ),
    ]
